### ISSUE TITLE
Merge target into official ANTLR project

### ISSUE THREAD

**Issue by KvanTTT** [Strumenta/antlr-kotlin#28]
Are you considering it? It will be simpler to maintain and keep in sync.

**Comment by ftomassetti** [comment]
Yes, this is something I would like to eventually do, however I am not sure about the effort required. Also because we would be targeting at least two platforms (browser and JVM), which is different from how other targets work.

Beside that I would like to be sure we have the right level of maturity for this target.

**Comment by ftomassetti** [comment]
Beside doing the merge we would then need to be sure we have the time to keep in sync and that could be not trivial, I think. Perhaps I should ask to maintainers of other targets

**Comment by drieks** [comment]
I think this is a duplicate of #14

**Comment by KvanTTT** [comment]
On then, I'm closing.
