### ISSUE TITLE
Group is ignored when publishing to local Maven repo

### ISSUE THREAD

**Issue by YoshiRulz** [Strumenta/antlr-kotlin#69]
I'm using `com.strumenta.antlr-kotlin:antlr-kotlin-*:6304d5c1c4` (6304d5c1c4). Running `gradle publishToMavenLocal` creates `~/.m2/repository/com/github/drieks/antlr-kotlin/<project>`. I have no idea why this is the case, @drieks' username doesn't even appear in the codebase.

edit: `gradle ... -Pgroup=... -Pversion=...` changed the output directory, but in any case I can't *use* it. There's no error about the import failing, only that the classes couldn't be found. Should I open a seperate issue for that?

**Comment by drieks** [comment]
Hi @YoshiRulz,

this is strange, when I'm running `./gradlew publishToMavenLocal` with java 11, it will be installed to `~/.m2/repository/com/strumenta/antlr-kotlin`. Note that I'm using the gradle wrapper script, otherwise, the local gradle version is used. but this should make no difference.

I'm using com/github/drieks/antlr-kotlin to publish my build of antlr-kotlin for https://github.com/kotlinx/ast, so I can publish a new version of kotlinx.ast without waiting for a PR here. (see https://github.com/kotlinx/ast/blob/master/buildSrc/src/main/kotlin/Versions.kt#L17)

I'm not building this version, it is build using jitpack: https://jitpack.io/#drieks/antlr-kotlin

As you can see in the build.log, he is running `./ci.sh -Pversion=$VERSION -Pgroup=$GROUP`: https://jitpack.io/com/github/drieks/antlr-kotlin/5d4f65ef83/build.loghttps://jitpack.io/com/github/drieks/antlr-kotlin/5d4f65ef83/build.log

Both VERSION and GROUP is set automatically by jitpack and ci.sh will pass it to gradlew.

Sadly, I don't know why you are getting my username.

Maybe you can try to delete the repository and check it out again? You can also try to run ci.sh, it will also invoke publishtoMavemLocal for you. What java version are you using?

**Comment by YoshiRulz** [comment]
When I went to upload a repro, I found the culprit—a `gradle.properties` file which must have been left over from a previous template I'd used. Sorry for wasting your time.

(And as for my edit, I got the project's immediate consumer to work by making the former a subproject of the latter, rather than publishing and importing from the local repo. Unfortunately I'm not then able to consume that from a third project. I think I'll shelve all of this, if any future humans would like some more example code it's [here](https://gitlab.com/YoshiRulz/Circulyr-ANTLR-attempt-2021).)
